<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GrupoOiSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('grupo_ois')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('grupo_ois')->insert([
            [
                'id' => 1,
                'parent_id' => null,
                'nome' => 'Recheio',
                'nivel' => 1,
                'ordem' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'parent_id' => 1,
                'nome' => 'Pré-obra',
                'nivel' => 2,
                'ordem' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'parent_id' => 1,
                'nome' => 'Civil',
                'nivel' => 2,
                'ordem' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'parent_id' => 1,
                'nome' => 'Instalações e Gerenciamento',
                'nivel' => 2,
                'ordem' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'parent_id' => 1,
                'nome' => 'Homologados',
                'nivel' => 2,
                'ordem' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'parent_id' => null,
                'nome' => 'Shell',
                'nivel' => 1,
                'ordem' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'parent_id' => 6,
                'nome' => 'Estrutura',
                'nivel' => 2,
                'ordem' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'parent_id' => 3,
                'nome' => 'Custos Administrativos',
                'nivel' => 3,
                'ordem' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'parent_id' => 3,
                'nome' => 'Serviços Preliminares',
                'nivel' => 3,
                'ordem' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'parent_id' => 3,
                'nome' => 'Paredes e Divisórias',
                'nivel' => 3,
                'ordem' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'parent_id' => 3,
                'nome' => 'Revestimentos de Paredes',
                'nivel' => 3,
                'ordem' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'parent_id' => 3,
                'nome' => 'Piso',
                'nivel' => 3,
                'ordem' => 5,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'parent_id' => 3,
                'nome' => 'Instalações Hidráulicas',
                'nivel' => 3,
                'ordem' => 6,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'parent_id' => 3,
                'nome' => 'Pintura',
                'nivel' => 3,
                'ordem' => 7,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'parent_id' => 3,
                'nome' => 'Vidros e Espelhos',
                'nivel' => 3,
                'ordem' => 8,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'parent_id' => 3,
                'nome' => 'Granitos',
                'nivel' => 3,
                'ordem' => 9,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'parent_id' => 3,
                'nome' => 'Esquadrias',
                'nivel' => 3,
                'ordem' => 10,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'parent_id' => 3,
                'nome' => 'Apoio Civil',
                'nivel' => 3,
                'ordem' => 11,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'parent_id' => 3,
                'nome' => 'Limpeza Permanente + Limpeza Fina',
                'nivel' => 3,
                'ordem' => 12,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'parent_id' => 3,
                'nome' => 'Omissos',
                'nivel' => 3,
                'ordem' => 13,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'parent_id' => 4,
                'nome' => 'Ar Condicionado / Exaustão',
                'nivel' => 3,
                'ordem' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'parent_id' => 4,
                'nome' => 'T.I e Sonorização',
                'nivel' => 3,
                'ordem' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'parent_id' => 4,
                'nome' => 'Instalações Elétricas',
                'nivel' => 3,
                'ordem' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'parent_id' => 4,
                'nome' => 'Combate a Incêndio',
                'nivel' => 3,
                'ordem' => 4,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'parent_id' => 5,
                'nome' => 'Piso / Revestimento',
                'nivel' => 3,
                'ordem' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'parent_id' => 5,
                'nome' => 'Luminárias',
                'nivel' => 3,
                'ordem' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'parent_id' => 5,
                'nome' => 'Fachada + Comunicação Visual',
                'nivel' => 3,
                'ordem' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'parent_id' => 7,
                'nome' => 'Demolições e Remoções',
                'nivel' => 3,
                'ordem' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
