<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use RuntimeException;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

final class LocalUserSeeder extends Seeder
{
    /**
     * Seeder manual para ambiente local.
     */
    public function run(): void
    {
        if (! app()->environment('local')) {
            throw new RuntimeException('LocalUserSeeder só pode ser executado no ambiente local.');
        }

        $data = $this->seedData();

        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $this->syncRolesAndPermissions($data['roles']);
        $this->syncUsers($data['users']);

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }

    /**
     * @return array{roles: array<string, array{guard_name: string, permissions: list<string>}>, users: list<array<string, mixed>>}
     */
    private function seedData(): array
    {
        return [
            'roles' => [
                'super_admin' => [
                    'guard_name' => 'web',
                    'permissions' => [
                        0 => 'Create:Ambientes',
                        1 => 'Create:AsEscopo',
                        2 => 'Create:Asa',
                        3 => 'Create:CadastrarCnpj',
                        4 => 'Create:Cidade',
                        5 => 'Create:Construtora',
                        6 => 'Create:ControlePedido',
                        7 => 'Create:Dados',
                        8 => 'Create:Departamentos',
                        9 => 'Create:ElaboracaoAditivo',
                        10 => 'Create:Empresas',
                        11 => 'Create:Estado',
                        12 => 'Create:Etapa',
                        13 => 'Create:Marca',
                        14 => 'Create:Matterport',
                        15 => 'Create:Obras',
                        16 => 'Create:Pais',
                        17 => 'Create:Pipe',
                        18 => 'Create:Projeto',
                        19 => 'Create:RelatorioFotografico',
                        20 => 'Create:RelatorioVisitaTecnica',
                        21 => 'Create:Role',
                        22 => 'Create:Setor',
                        23 => 'Create:Task',
                        24 => 'Create:TaskCategory',
                        25 => 'Create:User',
                        26 => 'Delete:Ambientes',
                        27 => 'Delete:AsEscopo',
                        28 => 'Delete:Asa',
                        29 => 'Delete:CadastrarCnpj',
                        30 => 'Delete:Cidade',
                        31 => 'Delete:Construtora',
                        32 => 'Delete:ControlePedido',
                        33 => 'Delete:Dados',
                        34 => 'Delete:Departamentos',
                        35 => 'Delete:ElaboracaoAditivo',
                        36 => 'Delete:Empresas',
                        37 => 'Delete:Estado',
                        38 => 'Delete:Etapa',
                        39 => 'Delete:Marca',
                        40 => 'Delete:Matterport',
                        41 => 'Delete:Obras',
                        42 => 'Delete:Pais',
                        43 => 'Delete:Pipe',
                        44 => 'Delete:Projeto',
                        45 => 'Delete:RelatorioFotografico',
                        46 => 'Delete:RelatorioVisitaTecnica',
                        47 => 'Delete:Role',
                        48 => 'Delete:Setor',
                        49 => 'Delete:Task',
                        50 => 'Delete:TaskCategory',
                        51 => 'Delete:User',
                        52 => 'ForceDelete:Ambientes',
                        53 => 'ForceDelete:AsEscopo',
                        54 => 'ForceDelete:Asa',
                        55 => 'ForceDelete:Cidade',
                        56 => 'ForceDelete:Construtora',
                        57 => 'ForceDelete:ControlePedido',
                        58 => 'ForceDelete:Dados',
                        59 => 'ForceDelete:Departamentos',
                        60 => 'ForceDelete:ElaboracaoAditivo',
                        61 => 'ForceDelete:Empresas',
                        62 => 'ForceDelete:Estado',
                        63 => 'ForceDelete:Etapa',
                        64 => 'ForceDelete:Marca',
                        65 => 'ForceDelete:Matterport',
                        66 => 'ForceDelete:Obras',
                        67 => 'ForceDelete:Pais',
                        68 => 'ForceDelete:Pipe',
                        69 => 'ForceDelete:Projeto',
                        70 => 'ForceDelete:RelatorioFotografico',
                        71 => 'ForceDelete:RelatorioVisitaTecnica',
                        72 => 'ForceDelete:Role',
                        73 => 'ForceDelete:Setor',
                        74 => 'ForceDelete:Task',
                        75 => 'ForceDelete:TaskCategory',
                        76 => 'ForceDelete:User',
                        77 => 'ForceDeleteAny:Ambientes',
                        78 => 'ForceDeleteAny:AsEscopo',
                        79 => 'ForceDeleteAny:Asa',
                        80 => 'ForceDeleteAny:Cidade',
                        81 => 'ForceDeleteAny:Construtora',
                        82 => 'ForceDeleteAny:ControlePedido',
                        83 => 'ForceDeleteAny:Dados',
                        84 => 'ForceDeleteAny:Departamentos',
                        85 => 'ForceDeleteAny:ElaboracaoAditivo',
                        86 => 'ForceDeleteAny:Empresas',
                        87 => 'ForceDeleteAny:Estado',
                        88 => 'ForceDeleteAny:Etapa',
                        89 => 'ForceDeleteAny:Marca',
                        90 => 'ForceDeleteAny:Matterport',
                        91 => 'ForceDeleteAny:Obras',
                        92 => 'ForceDeleteAny:Pais',
                        93 => 'ForceDeleteAny:Pipe',
                        94 => 'ForceDeleteAny:Projeto',
                        95 => 'ForceDeleteAny:RelatorioFotografico',
                        96 => 'ForceDeleteAny:RelatorioVisitaTecnica',
                        97 => 'ForceDeleteAny:Role',
                        98 => 'ForceDeleteAny:Setor',
                        99 => 'ForceDeleteAny:Task',
                        100 => 'ForceDeleteAny:TaskCategory',
                        101 => 'ForceDeleteAny:User',
                        102 => 'Reorder:Ambientes',
                        103 => 'Reorder:AsEscopo',
                        104 => 'Reorder:Asa',
                        105 => 'Reorder:Cidade',
                        106 => 'Reorder:Construtora',
                        107 => 'Reorder:ControlePedido',
                        108 => 'Reorder:Dados',
                        109 => 'Reorder:Departamentos',
                        110 => 'Reorder:ElaboracaoAditivo',
                        111 => 'Reorder:Empresas',
                        112 => 'Reorder:Estado',
                        113 => 'Reorder:Etapa',
                        114 => 'Reorder:Marca',
                        115 => 'Reorder:Matterport',
                        116 => 'Reorder:Obras',
                        117 => 'Reorder:Pais',
                        118 => 'Reorder:Pipe',
                        119 => 'Reorder:Projeto',
                        120 => 'Reorder:RelatorioFotografico',
                        121 => 'Reorder:RelatorioVisitaTecnica',
                        122 => 'Reorder:Role',
                        123 => 'Reorder:Setor',
                        124 => 'Reorder:Task',
                        125 => 'Reorder:TaskCategory',
                        126 => 'Reorder:User',
                        127 => 'Replicate:Ambientes',
                        128 => 'Replicate:AsEscopo',
                        129 => 'Replicate:Asa',
                        130 => 'Replicate:Cidade',
                        131 => 'Replicate:Construtora',
                        132 => 'Replicate:ControlePedido',
                        133 => 'Replicate:Dados',
                        134 => 'Replicate:Departamentos',
                        135 => 'Replicate:ElaboracaoAditivo',
                        136 => 'Replicate:Empresas',
                        137 => 'Replicate:Estado',
                        138 => 'Replicate:Etapa',
                        139 => 'Replicate:Marca',
                        140 => 'Replicate:Matterport',
                        141 => 'Replicate:Obras',
                        142 => 'Replicate:Pais',
                        143 => 'Replicate:Pipe',
                        144 => 'Replicate:Projeto',
                        145 => 'Replicate:RelatorioFotografico',
                        146 => 'Replicate:RelatorioVisitaTecnica',
                        147 => 'Replicate:Role',
                        148 => 'Replicate:Setor',
                        149 => 'Replicate:Task',
                        150 => 'Replicate:TaskCategory',
                        151 => 'Replicate:User',
                        152 => 'Restore:Ambientes',
                        153 => 'Restore:AsEscopo',
                        154 => 'Restore:Asa',
                        155 => 'Restore:Cidade',
                        156 => 'Restore:Construtora',
                        157 => 'Restore:ControlePedido',
                        158 => 'Restore:Dados',
                        159 => 'Restore:Departamentos',
                        160 => 'Restore:ElaboracaoAditivo',
                        161 => 'Restore:Empresas',
                        162 => 'Restore:Estado',
                        163 => 'Restore:Etapa',
                        164 => 'Restore:Marca',
                        165 => 'Restore:Matterport',
                        166 => 'Restore:Obras',
                        167 => 'Restore:Pais',
                        168 => 'Restore:Pipe',
                        169 => 'Restore:Projeto',
                        170 => 'Restore:RelatorioFotografico',
                        171 => 'Restore:RelatorioVisitaTecnica',
                        172 => 'Restore:Role',
                        173 => 'Restore:Setor',
                        174 => 'Restore:Task',
                        175 => 'Restore:TaskCategory',
                        176 => 'Restore:User',
                        177 => 'RestoreAny:Ambientes',
                        178 => 'RestoreAny:AsEscopo',
                        179 => 'RestoreAny:Asa',
                        180 => 'RestoreAny:Cidade',
                        181 => 'RestoreAny:Construtora',
                        182 => 'RestoreAny:ControlePedido',
                        183 => 'RestoreAny:Dados',
                        184 => 'RestoreAny:Departamentos',
                        185 => 'RestoreAny:ElaboracaoAditivo',
                        186 => 'RestoreAny:Empresas',
                        187 => 'RestoreAny:Estado',
                        188 => 'RestoreAny:Etapa',
                        189 => 'RestoreAny:Marca',
                        190 => 'RestoreAny:Matterport',
                        191 => 'RestoreAny:Obras',
                        192 => 'RestoreAny:Pais',
                        193 => 'RestoreAny:Pipe',
                        194 => 'RestoreAny:Projeto',
                        195 => 'RestoreAny:RelatorioFotografico',
                        196 => 'RestoreAny:RelatorioVisitaTecnica',
                        197 => 'RestoreAny:Role',
                        198 => 'RestoreAny:Setor',
                        199 => 'RestoreAny:Task',
                        200 => 'RestoreAny:TaskCategory',
                        201 => 'RestoreAny:User',
                        202 => 'Update:Ambientes',
                        203 => 'Update:AsEscopo',
                        204 => 'Update:Asa',
                        205 => 'Update:CadastrarCnpj',
                        206 => 'Update:Cidade',
                        207 => 'Update:Construtora',
                        208 => 'Update:ControlePedido',
                        209 => 'Update:Dados',
                        210 => 'Update:Departamentos',
                        211 => 'Update:ElaboracaoAditivo',
                        212 => 'Update:Empresas',
                        213 => 'Update:Estado',
                        214 => 'Update:Etapa',
                        215 => 'Update:Marca',
                        216 => 'Update:Matterport',
                        217 => 'Update:Obras',
                        218 => 'Update:Pais',
                        219 => 'Update:Pipe',
                        220 => 'Update:Projeto',
                        221 => 'Update:RelatorioFotografico',
                        222 => 'Update:RelatorioVisitaTecnica',
                        223 => 'Update:Role',
                        224 => 'Update:Setor',
                        225 => 'Update:Task',
                        226 => 'Update:TaskCategory',
                        227 => 'Update:User',
                        228 => 'View:AgendaVtComercial',
                        229 => 'View:Ambientes',
                        230 => 'View:ApexGraficoAcompanhamento',
                        231 => 'View:AsEscopo',
                        232 => 'View:Asa',
                        233 => 'View:CadastrarPonto',
                        234 => 'View:Cidade',
                        235 => 'View:Construtora',
                        236 => 'View:ControlePedido',
                        237 => 'View:Dados',
                        238 => 'View:Dashboard',
                        239 => 'View:DashboardColaOrc',
                        240 => 'View:DashboardColaborador',
                        241 => 'View:DashboardComercial',
                        242 => 'View:DashboardComercialCoordenacao',
                        243 => 'View:DashboardOI',
                        244 => 'View:DashboardPedidos',
                        245 => 'View:DashboardTarefas',
                        246 => 'View:Departamentos',
                        247 => 'View:ElaboracaoAditivo',
                        248 => 'View:Empresas',
                        249 => 'View:Estado',
                        250 => 'View:Etapa',
                        251 => 'View:HistoricoProjetoCustom',
                        252 => 'View:ImportObras',
                        253 => 'View:LandBank',
                        254 => 'View:MapaGeral',
                        255 => 'View:MapaObras',
                        256 => 'View:MapaStatus',
                        257 => 'View:Marca',
                        258 => 'View:Matterport',
                        259 => 'View:Obras',
                        260 => 'View:Pais',
                        261 => 'View:Pipe',
                        262 => 'View:Projeto',
                        263 => 'View:ProjetosDashboard',
                        264 => 'View:ProjetosInauguradosOverview',
                        265 => 'View:ProjetosMapa',
                        266 => 'View:RelatorioFotografico',
                        267 => 'View:RelatorioVisitaTecnica',
                        268 => 'View:ResumoSemanalTasks',
                        269 => 'View:RiscosDetalhadosTable',
                        270 => 'View:RiscosDonutChart',
                        271 => 'View:RiscosTable',
                        272 => 'View:Role',
                        273 => 'View:Setor',
                        274 => 'View:SimuladorCapex',
                        275 => 'View:TableAcompanhamento',
                        276 => 'View:Task',
                        277 => 'View:TaskCategory',
                        278 => 'View:User',
                        279 => 'View:VisualizarPipe',
                        280 => 'ViewAny:Ambientes',
                        281 => 'ViewAny:AsEscopo',
                        282 => 'ViewAny:Asa',
                        283 => 'ViewAny:Cidade',
                        284 => 'ViewAny:Construtora',
                        285 => 'ViewAny:ControlePedido',
                        286 => 'ViewAny:Dados',
                        287 => 'ViewAny:Departamentos',
                        288 => 'ViewAny:ElaboracaoAditivo',
                        289 => 'ViewAny:Empresas',
                        290 => 'ViewAny:Estado',
                        291 => 'ViewAny:Etapa',
                        292 => 'ViewAny:Marca',
                        293 => 'ViewAny:Matterport',
                        294 => 'ViewAny:Obras',
                        295 => 'ViewAny:Pais',
                        296 => 'ViewAny:Pipe',
                        297 => 'ViewAny:Projeto',
                        298 => 'ViewAny:RelatorioFotografico',
                        299 => 'ViewAny:RelatorioVisitaTecnica',
                        300 => 'ViewAny:Role',
                        301 => 'ViewAny:Setor',
                        302 => 'ViewAny:Task',
                        303 => 'ViewAny:TaskCategory',
                        304 => 'ViewAny:User',
                        305 => 'View:Cronograma',
                        306 => 'View:CronogramaTemplates',
                        307 => 'ZerarDatas:Cronograma',
                        308 => 'View:AgendaGeral',
                        309 => 'View:AprovacaoMudancaPosse',
                        310 => 'View:AprovacaoNotasFiscaisPage',
                        311 => 'View:AutorizacaoServico',
                        312 => 'CancelApproved:AutorizacaoServico',
                        313 => 'View:FinanceiroNotasFiscais',
                        314 => 'View:HistoricoProjetos',
                        315 => 'View:ImportarMkt',
                        316 => 'Close:ControleNotaFiscal',
                    ],
                ],
                'coordenador_orcamento' => [
                    'guard_name' => 'web',
                    'permissions' => [
                        0 => 'Create:ControlePedido',
                        1 => 'Create:Task',
                        2 => 'Create:TaskCategory',
                        3 => 'Create:User',
                        4 => 'Delete:ControlePedido',
                        5 => 'Delete:Task',
                        6 => 'Delete:TaskCategory',
                        7 => 'Delete:User',
                        8 => 'ForceDelete:ControlePedido',
                        9 => 'ForceDelete:Task',
                        10 => 'ForceDelete:TaskCategory',
                        11 => 'ForceDelete:User',
                        12 => 'ForceDeleteAny:ControlePedido',
                        13 => 'ForceDeleteAny:Task',
                        14 => 'ForceDeleteAny:TaskCategory',
                        15 => 'ForceDeleteAny:User',
                        16 => 'Reorder:ControlePedido',
                        17 => 'Reorder:Task',
                        18 => 'Reorder:TaskCategory',
                        19 => 'Reorder:User',
                        20 => 'Replicate:ControlePedido',
                        21 => 'Replicate:Task',
                        22 => 'Replicate:TaskCategory',
                        23 => 'Replicate:User',
                        24 => 'Restore:ControlePedido',
                        25 => 'Restore:Task',
                        26 => 'Restore:TaskCategory',
                        27 => 'Restore:User',
                        28 => 'RestoreAny:ControlePedido',
                        29 => 'RestoreAny:Task',
                        30 => 'RestoreAny:TaskCategory',
                        31 => 'RestoreAny:User',
                        32 => 'Update:ControlePedido',
                        33 => 'Update:Task',
                        34 => 'Update:TaskCategory',
                        35 => 'Update:User',
                        36 => 'View:ControlePedido',
                        37 => 'View:Dashboard',
                        38 => 'View:DashboardOI',
                        39 => 'View:DashboardPedidos',
                        40 => 'View:SimuladorCapex',
                        41 => 'View:Task',
                        42 => 'View:TaskCategory',
                        43 => 'View:User',
                        44 => 'ViewAny:ControlePedido',
                        45 => 'ViewAny:Task',
                        46 => 'ViewAny:TaskCategory',
                        47 => 'ViewAny:User',
                    ],
                ],
                'colaborador_orcamento' => [
                    'guard_name' => 'web',
                    'permissions' => [
                        0 => 'Create:ControlePedido',
                        1 => 'Create:Task',
                        2 => 'Delete:ControlePedido',
                        3 => 'Delete:Task',
                        4 => 'ForceDelete:ControlePedido',
                        5 => 'ForceDelete:Task',
                        6 => 'ForceDeleteAny:ControlePedido',
                        7 => 'ForceDeleteAny:Task',
                        8 => 'Reorder:ControlePedido',
                        9 => 'Reorder:Task',
                        10 => 'Replicate:ControlePedido',
                        11 => 'Replicate:Task',
                        12 => 'Restore:ControlePedido',
                        13 => 'Restore:Task',
                        14 => 'RestoreAny:ControlePedido',
                        15 => 'RestoreAny:Task',
                        16 => 'Update:ControlePedido',
                        17 => 'Update:Task',
                        18 => 'View:ControlePedido',
                        19 => 'View:Dashboard',
                        20 => 'View:DashboardColaOrc',
                        21 => 'View:DashboardOI',
                        22 => 'View:DashboardPedidos',
                        23 => 'View:SimuladorCapex',
                        24 => 'View:Task',
                        25 => 'ViewAny:ControlePedido',
                        26 => 'ViewAny:Task',
                    ],
                ],
                'Colaborador' => [
                    'guard_name' => 'web',
                    'permissions' => [
                        0 => 'Create:Task',
                        1 => 'Delete:Task',
                        2 => 'ForceDelete:Task',
                        3 => 'ForceDeleteAny:Task',
                        4 => 'Reorder:Task',
                        5 => 'Replicate:Task',
                        6 => 'Restore:Task',
                        7 => 'RestoreAny:Task',
                        8 => 'Update:Task',
                        9 => 'View:Dashboard',
                        10 => 'View:DashboardColaborador',
                        11 => 'View:Task',
                        12 => 'ViewAny:Task',
                    ],
                ],
                'PMO' => [
                    'guard_name' => 'web',
                    'permissions' => [
                        0 => 'Create:Projeto',
                        1 => 'Delete:Projeto',
                        2 => 'ForceDelete:Projeto',
                        3 => 'ForceDeleteAny:Projeto',
                        4 => 'Reorder:Projeto',
                        5 => 'Replicate:Projeto',
                        6 => 'Restore:Projeto',
                        7 => 'RestoreAny:Projeto',
                        8 => 'Update:Projeto',
                        9 => 'View:Projeto',
                        10 => 'ViewAny:Projeto',
                    ],
                ],
                'Comercial' => [
                    'guard_name' => 'web',
                    'permissions' => [
                        0 => 'Create:Task',
                        1 => 'Delete:Task',
                        2 => 'ForceDelete:Task',
                        3 => 'ForceDeleteAny:Task',
                        4 => 'Reorder:Task',
                        5 => 'Replicate:Task',
                        6 => 'Restore:Task',
                        7 => 'RestoreAny:Task',
                        8 => 'Update:Task',
                        9 => 'View:AgendaVtComercial',
                        10 => 'View:CadastrarPonto',
                        11 => 'View:DashboardComercial',
                        12 => 'View:DashboardComercialCoordenacao',
                        13 => 'View:Task',
                        14 => 'ViewAny:Task',
                    ],
                ],
                'Arquitetura' => [
                    'guard_name' => 'web',
                    'permissions' => [
                        0 => 'Create:Projeto',
                        1 => 'Delete:Projeto',
                        2 => 'ForceDelete:Projeto',
                        3 => 'ForceDeleteAny:Projeto',
                        4 => 'Reorder:Projeto',
                        5 => 'Replicate:Projeto',
                        6 => 'Restore:Projeto',
                        7 => 'RestoreAny:Projeto',
                        8 => 'Update:Projeto',
                        9 => 'View:Projeto',
                        10 => 'ViewAny:Projeto',
                    ],
                ],
                'Engenharia' => [
                    'guard_name' => 'web',
                    'permissions' => [
                        0 => 'Create:Projeto',
                        1 => 'Delete:Projeto',
                        2 => 'ForceDelete:Projeto',
                        3 => 'ForceDeleteAny:Projeto',
                        4 => 'Reorder:Projeto',
                        5 => 'Replicate:Projeto',
                        6 => 'Restore:Projeto',
                        7 => 'RestoreAny:Projeto',
                        8 => 'Update:Projeto',
                        9 => 'View:Projeto',
                        10 => 'ViewAny:Projeto',
                    ],
                ],
                'gestor_obra' => [
                    'guard_name' => 'web',
                    'permissions' => [
                        0 => 'Create:Ambientes',
                        1 => 'Create:Cidade',
                        2 => 'Create:ControlePedido',
                        3 => 'Create:Dados',
                        4 => 'Create:Departamentos',
                        5 => 'Create:Empresas',
                        6 => 'Create:Estado',
                        7 => 'Create:Etapa',
                        8 => 'Create:Marca',
                        9 => 'Create:Matterport',
                        10 => 'Create:Obras',
                        11 => 'Create:Pais',
                        12 => 'Create:Pipe',
                        13 => 'Create:Projeto',
                        14 => 'Create:RelatorioFotografico',
                        15 => 'Create:RelatorioVisitaTecnica',
                        16 => 'Create:Role',
                        17 => 'Create:Setor',
                        18 => 'Create:Task',
                        19 => 'Create:TaskCategory',
                        20 => 'Create:User',
                        21 => 'Delete:Ambientes',
                        22 => 'Delete:Cidade',
                        23 => 'Delete:ControlePedido',
                        24 => 'Delete:Dados',
                        25 => 'Delete:Departamentos',
                        26 => 'Delete:Empresas',
                        27 => 'Delete:Estado',
                        28 => 'Delete:Etapa',
                        29 => 'Delete:Marca',
                        30 => 'Delete:Matterport',
                        31 => 'Delete:Obras',
                        32 => 'Delete:Pais',
                        33 => 'Delete:Pipe',
                        34 => 'Delete:Projeto',
                        35 => 'Delete:RelatorioFotografico',
                        36 => 'Delete:RelatorioVisitaTecnica',
                        37 => 'Delete:Role',
                        38 => 'Delete:Setor',
                        39 => 'Delete:Task',
                        40 => 'Delete:TaskCategory',
                        41 => 'Delete:User',
                        42 => 'ForceDelete:Ambientes',
                        43 => 'ForceDelete:Cidade',
                        44 => 'ForceDelete:ControlePedido',
                        45 => 'ForceDelete:Dados',
                        46 => 'ForceDelete:Departamentos',
                        47 => 'ForceDelete:Empresas',
                        48 => 'ForceDelete:Estado',
                        49 => 'ForceDelete:Etapa',
                        50 => 'ForceDelete:Marca',
                        51 => 'ForceDelete:Matterport',
                        52 => 'ForceDelete:Obras',
                        53 => 'ForceDelete:Pais',
                        54 => 'ForceDelete:Pipe',
                        55 => 'ForceDelete:Projeto',
                        56 => 'ForceDelete:RelatorioFotografico',
                        57 => 'ForceDelete:RelatorioVisitaTecnica',
                        58 => 'ForceDelete:Role',
                        59 => 'ForceDelete:Setor',
                        60 => 'ForceDelete:Task',
                        61 => 'ForceDelete:TaskCategory',
                        62 => 'ForceDelete:User',
                        63 => 'ForceDeleteAny:Ambientes',
                        64 => 'ForceDeleteAny:Cidade',
                        65 => 'ForceDeleteAny:ControlePedido',
                        66 => 'ForceDeleteAny:Dados',
                        67 => 'ForceDeleteAny:Departamentos',
                        68 => 'ForceDeleteAny:Empresas',
                        69 => 'ForceDeleteAny:Estado',
                        70 => 'ForceDeleteAny:Etapa',
                        71 => 'ForceDeleteAny:Marca',
                        72 => 'ForceDeleteAny:Matterport',
                        73 => 'ForceDeleteAny:Obras',
                        74 => 'ForceDeleteAny:Pais',
                        75 => 'ForceDeleteAny:Pipe',
                        76 => 'ForceDeleteAny:Projeto',
                        77 => 'ForceDeleteAny:RelatorioFotografico',
                        78 => 'ForceDeleteAny:RelatorioVisitaTecnica',
                        79 => 'ForceDeleteAny:Role',
                        80 => 'ForceDeleteAny:Setor',
                        81 => 'ForceDeleteAny:Task',
                        82 => 'ForceDeleteAny:TaskCategory',
                        83 => 'ForceDeleteAny:User',
                        84 => 'Reorder:Ambientes',
                        85 => 'Reorder:Cidade',
                        86 => 'Reorder:ControlePedido',
                        87 => 'Reorder:Dados',
                        88 => 'Reorder:Departamentos',
                        89 => 'Reorder:Empresas',
                        90 => 'Reorder:Estado',
                        91 => 'Reorder:Etapa',
                        92 => 'Reorder:Marca',
                        93 => 'Reorder:Matterport',
                        94 => 'Reorder:Obras',
                        95 => 'Reorder:Pais',
                        96 => 'Reorder:Pipe',
                        97 => 'Reorder:Projeto',
                        98 => 'Reorder:RelatorioFotografico',
                        99 => 'Reorder:RelatorioVisitaTecnica',
                        100 => 'Reorder:Role',
                        101 => 'Reorder:Setor',
                        102 => 'Reorder:Task',
                        103 => 'Reorder:TaskCategory',
                        104 => 'Reorder:User',
                        105 => 'Replicate:Ambientes',
                        106 => 'Replicate:Cidade',
                        107 => 'Replicate:ControlePedido',
                        108 => 'Replicate:Dados',
                        109 => 'Replicate:Departamentos',
                        110 => 'Replicate:Empresas',
                        111 => 'Replicate:Estado',
                        112 => 'Replicate:Etapa',
                        113 => 'Replicate:Marca',
                        114 => 'Replicate:Matterport',
                        115 => 'Replicate:Obras',
                        116 => 'Replicate:Pais',
                        117 => 'Replicate:Pipe',
                        118 => 'Replicate:Projeto',
                        119 => 'Replicate:RelatorioFotografico',
                        120 => 'Replicate:RelatorioVisitaTecnica',
                        121 => 'Replicate:Role',
                        122 => 'Replicate:Setor',
                        123 => 'Replicate:Task',
                        124 => 'Replicate:TaskCategory',
                        125 => 'Replicate:User',
                        126 => 'Restore:Ambientes',
                        127 => 'Restore:Cidade',
                        128 => 'Restore:ControlePedido',
                        129 => 'Restore:Dados',
                        130 => 'Restore:Departamentos',
                        131 => 'Restore:Empresas',
                        132 => 'Restore:Estado',
                        133 => 'Restore:Etapa',
                        134 => 'Restore:Marca',
                        135 => 'Restore:Matterport',
                        136 => 'Restore:Obras',
                        137 => 'Restore:Pais',
                        138 => 'Restore:Pipe',
                        139 => 'Restore:Projeto',
                        140 => 'Restore:RelatorioFotografico',
                        141 => 'Restore:RelatorioVisitaTecnica',
                        142 => 'Restore:Role',
                        143 => 'Restore:Setor',
                        144 => 'Restore:Task',
                        145 => 'Restore:TaskCategory',
                        146 => 'Restore:User',
                        147 => 'RestoreAny:Ambientes',
                        148 => 'RestoreAny:Cidade',
                        149 => 'RestoreAny:ControlePedido',
                        150 => 'RestoreAny:Dados',
                        151 => 'RestoreAny:Departamentos',
                        152 => 'RestoreAny:Empresas',
                        153 => 'RestoreAny:Estado',
                        154 => 'RestoreAny:Etapa',
                        155 => 'RestoreAny:Marca',
                        156 => 'RestoreAny:Matterport',
                        157 => 'RestoreAny:Obras',
                        158 => 'RestoreAny:Pais',
                        159 => 'RestoreAny:Pipe',
                        160 => 'RestoreAny:Projeto',
                        161 => 'RestoreAny:RelatorioFotografico',
                        162 => 'RestoreAny:RelatorioVisitaTecnica',
                        163 => 'RestoreAny:Role',
                        164 => 'RestoreAny:Setor',
                        165 => 'RestoreAny:Task',
                        166 => 'RestoreAny:TaskCategory',
                        167 => 'RestoreAny:User',
                        168 => 'Update:Ambientes',
                        169 => 'Update:Cidade',
                        170 => 'Update:ControlePedido',
                        171 => 'Update:Dados',
                        172 => 'Update:Departamentos',
                        173 => 'Update:Empresas',
                        174 => 'Update:Estado',
                        175 => 'Update:Etapa',
                        176 => 'Update:Marca',
                        177 => 'Update:Matterport',
                        178 => 'Update:Obras',
                        179 => 'Update:Pais',
                        180 => 'Update:Pipe',
                        181 => 'Update:Projeto',
                        182 => 'Update:RelatorioFotografico',
                        183 => 'Update:RelatorioVisitaTecnica',
                        184 => 'Update:Role',
                        185 => 'Update:Setor',
                        186 => 'Update:Task',
                        187 => 'Update:TaskCategory',
                        188 => 'Update:User',
                        189 => 'View:Ambientes',
                        190 => 'View:ApexGraficoAcompanhamento',
                        191 => 'View:Cidade',
                        192 => 'View:ControlePedido',
                        193 => 'View:Dados',
                        194 => 'View:Dashboard',
                        195 => 'View:DashboardColaOrc',
                        196 => 'View:DashboardColaborador',
                        197 => 'View:DashboardOI',
                        198 => 'View:DashboardPedidos',
                        199 => 'View:DashboardTarefas',
                        200 => 'View:Departamentos',
                        201 => 'View:Empresas',
                        202 => 'View:Estado',
                        203 => 'View:Etapa',
                        204 => 'View:HistoricoProjetoCustom',
                        205 => 'View:LandBank',
                        206 => 'View:MapaGeral',
                        207 => 'View:MapaObras',
                        208 => 'View:MapaStatus',
                        209 => 'View:Marca',
                        210 => 'View:Matterport',
                        211 => 'View:Obras',
                        212 => 'View:Pais',
                        213 => 'View:Pipe',
                        214 => 'View:Projeto',
                        215 => 'View:ProjetosDashboard',
                        216 => 'View:ProjetosInauguradosOverview',
                        217 => 'View:ProjetosMapa',
                        218 => 'View:RelatorioFotografico',
                        219 => 'View:RelatorioVisitaTecnica',
                        220 => 'View:RiscosDetalhadosTable',
                        221 => 'View:RiscosDonutChart',
                        222 => 'View:RiscosTable',
                        223 => 'View:Role',
                        224 => 'View:Setor',
                        225 => 'View:SimuladorCapex',
                        226 => 'View:TableAcompanhamento',
                        227 => 'View:Task',
                        228 => 'View:TaskCategory',
                        229 => 'View:User',
                        230 => 'View:Viewer3D',
                        231 => 'View:VisualizarPipe',
                        232 => 'ViewAny:Ambientes',
                        233 => 'ViewAny:Cidade',
                        234 => 'ViewAny:ControlePedido',
                        235 => 'ViewAny:Dados',
                        236 => 'ViewAny:Departamentos',
                        237 => 'ViewAny:Empresas',
                        238 => 'ViewAny:Estado',
                        239 => 'ViewAny:Etapa',
                        240 => 'ViewAny:Marca',
                        241 => 'ViewAny:Matterport',
                        242 => 'ViewAny:Obras',
                        243 => 'ViewAny:Pais',
                        244 => 'ViewAny:Pipe',
                        245 => 'ViewAny:Projeto',
                        246 => 'ViewAny:RelatorioFotografico',
                        247 => 'ViewAny:RelatorioVisitaTecnica',
                        248 => 'ViewAny:Role',
                        249 => 'ViewAny:Setor',
                        250 => 'ViewAny:Task',
                        251 => 'ViewAny:TaskCategory',
                        252 => 'ViewAny:User',
                    ],
                ],
                'Coordenador' => [
                    'guard_name' => 'web',
                    'permissions' => [
                        0 => 'Create:Cidade',
                        1 => 'Create:ControlePedido',
                        2 => 'Create:Empresas',
                        3 => 'Create:Estado',
                        4 => 'Create:Etapa',
                        5 => 'Create:Marca',
                        6 => 'Create:Matterport',
                        7 => 'Create:Pais',
                        8 => 'Create:Pipe',
                        9 => 'Create:Projeto',
                        10 => 'Create:RelatorioFotografico',
                        11 => 'Create:RelatorioVisitaTecnica',
                        12 => 'Create:Setor',
                        13 => 'Create:Task',
                        14 => 'Create:TaskCategory',
                        15 => 'Create:User',
                        16 => 'Delete:Cidade',
                        17 => 'Delete:ControlePedido',
                        18 => 'Delete:Empresas',
                        19 => 'Delete:Estado',
                        20 => 'Delete:Etapa',
                        21 => 'Delete:Marca',
                        22 => 'Delete:Matterport',
                        23 => 'Delete:Pais',
                        24 => 'Delete:Pipe',
                        25 => 'Delete:Projeto',
                        26 => 'Delete:RelatorioFotografico',
                        27 => 'Delete:RelatorioVisitaTecnica',
                        28 => 'Delete:Setor',
                        29 => 'Delete:Task',
                        30 => 'Delete:TaskCategory',
                        31 => 'Delete:User',
                        32 => 'ForceDelete:Cidade',
                        33 => 'ForceDelete:ControlePedido',
                        34 => 'ForceDelete:Empresas',
                        35 => 'ForceDelete:Estado',
                        36 => 'ForceDelete:Etapa',
                        37 => 'ForceDelete:Marca',
                        38 => 'ForceDelete:Matterport',
                        39 => 'ForceDelete:Pais',
                        40 => 'ForceDelete:Pipe',
                        41 => 'ForceDelete:Projeto',
                        42 => 'ForceDelete:RelatorioFotografico',
                        43 => 'ForceDelete:RelatorioVisitaTecnica',
                        44 => 'ForceDelete:Setor',
                        45 => 'ForceDelete:Task',
                        46 => 'ForceDelete:TaskCategory',
                        47 => 'ForceDelete:User',
                        48 => 'ForceDeleteAny:Cidade',
                        49 => 'ForceDeleteAny:ControlePedido',
                        50 => 'ForceDeleteAny:Empresas',
                        51 => 'ForceDeleteAny:Estado',
                        52 => 'ForceDeleteAny:Etapa',
                        53 => 'ForceDeleteAny:Marca',
                        54 => 'ForceDeleteAny:Matterport',
                        55 => 'ForceDeleteAny:Pais',
                        56 => 'ForceDeleteAny:Pipe',
                        57 => 'ForceDeleteAny:Projeto',
                        58 => 'ForceDeleteAny:RelatorioFotografico',
                        59 => 'ForceDeleteAny:RelatorioVisitaTecnica',
                        60 => 'ForceDeleteAny:Setor',
                        61 => 'ForceDeleteAny:Task',
                        62 => 'ForceDeleteAny:TaskCategory',
                        63 => 'ForceDeleteAny:User',
                        64 => 'Reorder:Cidade',
                        65 => 'Reorder:ControlePedido',
                        66 => 'Reorder:Empresas',
                        67 => 'Reorder:Estado',
                        68 => 'Reorder:Etapa',
                        69 => 'Reorder:Marca',
                        70 => 'Reorder:Matterport',
                        71 => 'Reorder:Pais',
                        72 => 'Reorder:Pipe',
                        73 => 'Reorder:Projeto',
                        74 => 'Reorder:RelatorioFotografico',
                        75 => 'Reorder:RelatorioVisitaTecnica',
                        76 => 'Reorder:Setor',
                        77 => 'Reorder:Task',
                        78 => 'Reorder:TaskCategory',
                        79 => 'Reorder:User',
                        80 => 'Replicate:Cidade',
                        81 => 'Replicate:ControlePedido',
                        82 => 'Replicate:Empresas',
                        83 => 'Replicate:Estado',
                        84 => 'Replicate:Etapa',
                        85 => 'Replicate:Marca',
                        86 => 'Replicate:Matterport',
                        87 => 'Replicate:Pais',
                        88 => 'Replicate:Pipe',
                        89 => 'Replicate:Projeto',
                        90 => 'Replicate:RelatorioFotografico',
                        91 => 'Replicate:RelatorioVisitaTecnica',
                        92 => 'Replicate:Setor',
                        93 => 'Replicate:Task',
                        94 => 'Replicate:TaskCategory',
                        95 => 'Replicate:User',
                        96 => 'Restore:Cidade',
                        97 => 'Restore:ControlePedido',
                        98 => 'Restore:Empresas',
                        99 => 'Restore:Estado',
                        100 => 'Restore:Etapa',
                        101 => 'Restore:Marca',
                        102 => 'Restore:Matterport',
                        103 => 'Restore:Pais',
                        104 => 'Restore:Pipe',
                        105 => 'Restore:Projeto',
                        106 => 'Restore:RelatorioFotografico',
                        107 => 'Restore:RelatorioVisitaTecnica',
                        108 => 'Restore:Setor',
                        109 => 'Restore:Task',
                        110 => 'Restore:TaskCategory',
                        111 => 'Restore:User',
                        112 => 'RestoreAny:Cidade',
                        113 => 'RestoreAny:ControlePedido',
                        114 => 'RestoreAny:Empresas',
                        115 => 'RestoreAny:Estado',
                        116 => 'RestoreAny:Etapa',
                        117 => 'RestoreAny:Marca',
                        118 => 'RestoreAny:Matterport',
                        119 => 'RestoreAny:Pais',
                        120 => 'RestoreAny:Pipe',
                        121 => 'RestoreAny:Projeto',
                        122 => 'RestoreAny:RelatorioFotografico',
                        123 => 'RestoreAny:RelatorioVisitaTecnica',
                        124 => 'RestoreAny:Setor',
                        125 => 'RestoreAny:Task',
                        126 => 'RestoreAny:TaskCategory',
                        127 => 'RestoreAny:User',
                        128 => 'Update:Cidade',
                        129 => 'Update:ControlePedido',
                        130 => 'Update:Empresas',
                        131 => 'Update:Estado',
                        132 => 'Update:Etapa',
                        133 => 'Update:Marca',
                        134 => 'Update:Matterport',
                        135 => 'Update:Pais',
                        136 => 'Update:Pipe',
                        137 => 'Update:Projeto',
                        138 => 'Update:RelatorioFotografico',
                        139 => 'Update:RelatorioVisitaTecnica',
                        140 => 'Update:Setor',
                        141 => 'Update:Task',
                        142 => 'Update:TaskCategory',
                        143 => 'Update:User',
                        144 => 'View:Cidade',
                        145 => 'View:ControlePedido',
                        146 => 'View:Dashboard',
                        147 => 'View:DashboardOI',
                        148 => 'View:DashboardPedidos',
                        149 => 'View:DashboardTarefas',
                        150 => 'View:Empresas',
                        151 => 'View:Estado',
                        152 => 'View:Etapa',
                        153 => 'View:LandBank',
                        154 => 'View:Marca',
                        155 => 'View:Matterport',
                        156 => 'View:Pais',
                        157 => 'View:Pipe',
                        158 => 'View:Projeto',
                        159 => 'View:ProjetosDashboard',
                        160 => 'View:RelatorioFotografico',
                        161 => 'View:RelatorioVisitaTecnica',
                        162 => 'View:Setor',
                        163 => 'View:SimuladorCapex',
                        164 => 'View:Task',
                        165 => 'View:TaskCategory',
                        166 => 'View:User',
                        167 => 'View:Viewer3D',
                        168 => 'View:VisualizarPipe',
                        169 => 'ViewAny:Cidade',
                        170 => 'ViewAny:ControlePedido',
                        171 => 'ViewAny:Empresas',
                        172 => 'ViewAny:Estado',
                        173 => 'ViewAny:Etapa',
                        174 => 'ViewAny:Marca',
                        175 => 'ViewAny:Matterport',
                        176 => 'ViewAny:Pais',
                        177 => 'ViewAny:Pipe',
                        178 => 'ViewAny:Projeto',
                        179 => 'ViewAny:RelatorioFotografico',
                        180 => 'ViewAny:RelatorioVisitaTecnica',
                        181 => 'ViewAny:Setor',
                        182 => 'ViewAny:Task',
                        183 => 'ViewAny:TaskCategory',
                        184 => 'ViewAny:User',
                    ],
                ],
                'Gestor' => [
                    'guard_name' => 'web',
                    'permissions' => [
                        0 => 'Create:Cidade',
                        1 => 'Create:Empresas',
                        2 => 'Create:Estado',
                        3 => 'Create:Etapa',
                        4 => 'Create:Marca',
                        5 => 'Create:Matterport',
                        6 => 'Create:Obras',
                        7 => 'Create:Pais',
                        8 => 'Create:Pipe',
                        9 => 'Create:Projeto',
                        10 => 'Create:RelatorioFotografico',
                        11 => 'Create:RelatorioVisitaTecnica',
                        12 => 'Create:Setor',
                        13 => 'Create:Task',
                        14 => 'Create:TaskCategory',
                        15 => 'Create:User',
                        16 => 'Delete:Cidade',
                        17 => 'Delete:Empresas',
                        18 => 'Delete:Estado',
                        19 => 'Delete:Etapa',
                        20 => 'Delete:Marca',
                        21 => 'Delete:Matterport',
                        22 => 'Delete:Obras',
                        23 => 'Delete:Pais',
                        24 => 'Delete:Pipe',
                        25 => 'Delete:Projeto',
                        26 => 'Delete:RelatorioFotografico',
                        27 => 'Delete:RelatorioVisitaTecnica',
                        28 => 'Delete:Setor',
                        29 => 'Delete:Task',
                        30 => 'Delete:TaskCategory',
                        31 => 'Delete:User',
                        32 => 'ForceDelete:Cidade',
                        33 => 'ForceDelete:Empresas',
                        34 => 'ForceDelete:Estado',
                        35 => 'ForceDelete:Etapa',
                        36 => 'ForceDelete:Marca',
                        37 => 'ForceDelete:Matterport',
                        38 => 'ForceDelete:Obras',
                        39 => 'ForceDelete:Pais',
                        40 => 'ForceDelete:Pipe',
                        41 => 'ForceDelete:Projeto',
                        42 => 'ForceDelete:RelatorioFotografico',
                        43 => 'ForceDelete:RelatorioVisitaTecnica',
                        44 => 'ForceDelete:Setor',
                        45 => 'ForceDelete:Task',
                        46 => 'ForceDelete:TaskCategory',
                        47 => 'ForceDelete:User',
                        48 => 'ForceDeleteAny:Cidade',
                        49 => 'ForceDeleteAny:Empresas',
                        50 => 'ForceDeleteAny:Estado',
                        51 => 'ForceDeleteAny:Etapa',
                        52 => 'ForceDeleteAny:Marca',
                        53 => 'ForceDeleteAny:Matterport',
                        54 => 'ForceDeleteAny:Obras',
                        55 => 'ForceDeleteAny:Pais',
                        56 => 'ForceDeleteAny:Pipe',
                        57 => 'ForceDeleteAny:Projeto',
                        58 => 'ForceDeleteAny:RelatorioFotografico',
                        59 => 'ForceDeleteAny:RelatorioVisitaTecnica',
                        60 => 'ForceDeleteAny:Setor',
                        61 => 'ForceDeleteAny:Task',
                        62 => 'ForceDeleteAny:TaskCategory',
                        63 => 'ForceDeleteAny:User',
                        64 => 'Reorder:Cidade',
                        65 => 'Reorder:Empresas',
                        66 => 'Reorder:Estado',
                        67 => 'Reorder:Etapa',
                        68 => 'Reorder:Marca',
                        69 => 'Reorder:Matterport',
                        70 => 'Reorder:Obras',
                        71 => 'Reorder:Pais',
                        72 => 'Reorder:Pipe',
                        73 => 'Reorder:Projeto',
                        74 => 'Reorder:RelatorioFotografico',
                        75 => 'Reorder:RelatorioVisitaTecnica',
                        76 => 'Reorder:Setor',
                        77 => 'Reorder:Task',
                        78 => 'Reorder:TaskCategory',
                        79 => 'Reorder:User',
                        80 => 'Replicate:Cidade',
                        81 => 'Replicate:Empresas',
                        82 => 'Replicate:Estado',
                        83 => 'Replicate:Etapa',
                        84 => 'Replicate:Marca',
                        85 => 'Replicate:Matterport',
                        86 => 'Replicate:Obras',
                        87 => 'Replicate:Pais',
                        88 => 'Replicate:Pipe',
                        89 => 'Replicate:Projeto',
                        90 => 'Replicate:RelatorioFotografico',
                        91 => 'Replicate:RelatorioVisitaTecnica',
                        92 => 'Replicate:Setor',
                        93 => 'Replicate:Task',
                        94 => 'Replicate:TaskCategory',
                        95 => 'Replicate:User',
                        96 => 'Restore:Cidade',
                        97 => 'Restore:Empresas',
                        98 => 'Restore:Estado',
                        99 => 'Restore:Etapa',
                        100 => 'Restore:Marca',
                        101 => 'Restore:Matterport',
                        102 => 'Restore:Obras',
                        103 => 'Restore:Pais',
                        104 => 'Restore:Pipe',
                        105 => 'Restore:Projeto',
                        106 => 'Restore:RelatorioFotografico',
                        107 => 'Restore:RelatorioVisitaTecnica',
                        108 => 'Restore:Setor',
                        109 => 'Restore:Task',
                        110 => 'Restore:TaskCategory',
                        111 => 'Restore:User',
                        112 => 'RestoreAny:Cidade',
                        113 => 'RestoreAny:Empresas',
                        114 => 'RestoreAny:Estado',
                        115 => 'RestoreAny:Etapa',
                        116 => 'RestoreAny:Marca',
                        117 => 'RestoreAny:Matterport',
                        118 => 'RestoreAny:Obras',
                        119 => 'RestoreAny:Pais',
                        120 => 'RestoreAny:Pipe',
                        121 => 'RestoreAny:Projeto',
                        122 => 'RestoreAny:RelatorioFotografico',
                        123 => 'RestoreAny:RelatorioVisitaTecnica',
                        124 => 'RestoreAny:Setor',
                        125 => 'RestoreAny:Task',
                        126 => 'RestoreAny:TaskCategory',
                        127 => 'RestoreAny:User',
                        128 => 'Update:Cidade',
                        129 => 'Update:Empresas',
                        130 => 'Update:Estado',
                        131 => 'Update:Etapa',
                        132 => 'Update:Marca',
                        133 => 'Update:Matterport',
                        134 => 'Update:Obras',
                        135 => 'Update:Pais',
                        136 => 'Update:Pipe',
                        137 => 'Update:Projeto',
                        138 => 'Update:RelatorioFotografico',
                        139 => 'Update:RelatorioVisitaTecnica',
                        140 => 'Update:Setor',
                        141 => 'Update:Task',
                        142 => 'Update:TaskCategory',
                        143 => 'Update:User',
                        144 => 'View:AgendaVtComercial',
                        145 => 'View:CadastrarPonto',
                        146 => 'View:Cidade',
                        147 => 'View:Dashboard',
                        148 => 'View:DashboardComercial',
                        149 => 'View:DashboardComercialCoordenacao',
                        150 => 'View:DashboardOI',
                        151 => 'View:DashboardTarefas',
                        152 => 'View:Empresas',
                        153 => 'View:Estado',
                        154 => 'View:Etapa',
                        155 => 'View:LandBank',
                        156 => 'View:Marca',
                        157 => 'View:Matterport',
                        158 => 'View:Obras',
                        159 => 'View:Pais',
                        160 => 'View:Pipe',
                        161 => 'View:Projeto',
                        162 => 'View:ProjetosDashboard',
                        163 => 'View:ProjetosMapa',
                        164 => 'View:RelatorioFotografico',
                        165 => 'View:RelatorioVisitaTecnica',
                        166 => 'View:Setor',
                        167 => 'View:Task',
                        168 => 'View:TaskCategory',
                        169 => 'View:User',
                        170 => 'View:VisualizarPipe',
                        171 => 'ViewAny:Cidade',
                        172 => 'ViewAny:Empresas',
                        173 => 'ViewAny:Estado',
                        174 => 'ViewAny:Etapa',
                        175 => 'ViewAny:Marca',
                        176 => 'ViewAny:Matterport',
                        177 => 'ViewAny:Obras',
                        178 => 'ViewAny:Pais',
                        179 => 'ViewAny:Pipe',
                        180 => 'ViewAny:Projeto',
                        181 => 'ViewAny:RelatorioFotografico',
                        182 => 'ViewAny:RelatorioVisitaTecnica',
                        183 => 'ViewAny:Setor',
                        184 => 'ViewAny:Task',
                        185 => 'ViewAny:TaskCategory',
                        186 => 'ViewAny:User',
                    ],
                ],
                'Colaborador Obras' => [
                    'guard_name' => 'web',
                    'permissions' => [
                        0 => 'Create:RelatorioFotografico',
                        1 => 'Create:RelatorioVisitaTecnica',
                        2 => 'Delete:RelatorioFotografico',
                        3 => 'Delete:RelatorioVisitaTecnica',
                        4 => 'ForceDelete:RelatorioFotografico',
                        5 => 'ForceDelete:RelatorioVisitaTecnica',
                        6 => 'ForceDeleteAny:RelatorioFotografico',
                        7 => 'ForceDeleteAny:RelatorioVisitaTecnica',
                        8 => 'Reorder:RelatorioFotografico',
                        9 => 'Reorder:RelatorioVisitaTecnica',
                        10 => 'Replicate:RelatorioFotografico',
                        11 => 'Replicate:RelatorioVisitaTecnica',
                        12 => 'Restore:RelatorioFotografico',
                        13 => 'Restore:RelatorioVisitaTecnica',
                        14 => 'RestoreAny:RelatorioFotografico',
                        15 => 'RestoreAny:RelatorioVisitaTecnica',
                        16 => 'Update:RelatorioFotografico',
                        17 => 'Update:RelatorioVisitaTecnica',
                        18 => 'View:RelatorioFotografico',
                        19 => 'View:RelatorioVisitaTecnica',
                        20 => 'ViewAny:RelatorioFotografico',
                        21 => 'ViewAny:RelatorioVisitaTecnica',
                    ],
                ],
                'Fornecedor' => [
                    'guard_name' => 'web',
                    'permissions' => [
                        0 => 'Create:AsEscopo',
                        1 => 'Create:Construtora',
                        2 => 'Create:ControleNotaFiscalNota',
                        3 => 'Create:Task',
                        4 => 'Delete:AsEscopo',
                        5 => 'Delete:Construtora',
                        6 => 'Delete:Task',
                        7 => 'ForceDelete:AsEscopo',
                        8 => 'ForceDelete:Construtora',
                        9 => 'ForceDelete:Task',
                        10 => 'ForceDeleteAny:AsEscopo',
                        11 => 'ForceDeleteAny:Construtora',
                        12 => 'ForceDeleteAny:Task',
                        13 => 'Reorder:AsEscopo',
                        14 => 'Reorder:Construtora',
                        15 => 'Reorder:Task',
                        16 => 'Replicate:AsEscopo',
                        17 => 'Replicate:Construtora',
                        18 => 'Replicate:Task',
                        19 => 'Restore:AsEscopo',
                        20 => 'Restore:Construtora',
                        21 => 'Restore:Task',
                        22 => 'RestoreAny:AsEscopo',
                        23 => 'RestoreAny:Construtora',
                        24 => 'RestoreAny:Task',
                        25 => 'Update:AsEscopo',
                        26 => 'Update:Construtora',
                        27 => 'Update:Task',
                        28 => 'View:AsEscopo',
                        29 => 'View:CadastrarCnpj',
                        30 => 'View:Construtora',
                        31 => 'View:ConstrutoraControlesNotaFiscalPage',
                        32 => 'View:ControleNotaFiscalNota',
                        33 => 'View:Task',
                        34 => 'ViewAny:AsEscopo',
                        35 => 'ViewAny:CadastrarCnpj',
                        36 => 'ViewAny:Construtora',
                        37 => 'ViewAny:ControleNotaFiscalNota',
                        38 => 'ViewAny:Task',
                    ],
                ],
                'Consultor' => [
                    'guard_name' => 'web',
                    'permissions' => [
                        0 => 'Create:Task',
                        1 => 'Delete:Task',
                        2 => 'ForceDelete:Task',
                        3 => 'ForceDeleteAny:Task',
                        4 => 'Reorder:Task',
                        5 => 'Replicate:Task',
                        6 => 'Restore:Task',
                        7 => 'RestoreAny:Task',
                        8 => 'Update:Task',
                        9 => 'View:Task',
                        10 => 'ViewAny:Task',
                    ],
                ],
            ],
            'users' => [
                0 => [
                    'name' => 'Super Admin',
                    'email' => 'super.admin@example.test',
                    'phone' => null,
                    'password' => 'password',
                    'is_active' => true,
                    'is_fornecedor' => false,
                    'is_lider_obra' => false,
                    'construtoras_id' => null,
                    'must_change_password' => false,
                    'roles' => [
                        0 => 'super_admin',
                    ],
                ],
                1 => [
                    'name' => 'Gestor Obra',
                    'email' => 'gestor.obra@example.test',
                    'phone' => null,
                    'password' => 'password',
                    'is_active' => true,
                    'is_fornecedor' => false,
                    'is_lider_obra' => true,
                    'construtoras_id' => null,
                    'must_change_password' => false,
                    'roles' => [
                        0 => 'Gestor',
                        1 => 'Engenharia',
                        2 => 'Arquitetura',
                    ],
                ],
                2 => [
                    'name' => 'Coordenador Obra',
                    'email' => 'coordenador.obra@example.test',
                    'phone' => null,
                    'password' => 'password',
                    'is_active' => true,
                    'is_fornecedor' => false,
                    'is_lider_obra' => true,
                    'construtoras_id' => null,
                    'must_change_password' => false,
                    'roles' => [
                        0 => 'Coordenador',
                    ],
                ],
                3 => [
                    'name' => 'Coordenador Orcamentos',
                    'email' => 'coordenador.orcamentos@example.test',
                    'phone' => null,
                    'password' => 'password',
                    'is_active' => true,
                    'is_fornecedor' => false,
                    'is_lider_obra' => false,
                    'construtoras_id' => null,
                    'must_change_password' => false,
                    'roles' => [
                        0 => 'coordenador_orcamento',
                    ],
                ],
                4 => [
                    'name' => 'Fornecedor Terceiros',
                    'email' => 'fornecedor.terceiros@example.test',
                    'phone' => null,
                    'password' => 'password',
                    'is_active' => true,
                    'is_fornecedor' => true,
                    'is_lider_obra' => false,
                    'construtoras_id' => null,
                    'construtora_nome' => 'Fornecedor Demo Local',
                    'must_change_password' => false,
                    'roles' => [
                        0 => 'Fornecedor',
                    ],
                ],
                5 => [
                    'name' => 'Fornecedor Obra',
                    'email' => 'fornecedor.obra@example.test',
                    'phone' => null,
                    'password' => 'password',
                    'is_active' => true,
                    'is_fornecedor' => true,
                    'is_lider_obra' => false,
                    'construtoras_id' => null,
                    'construtora_nome' => 'Fornecedor Demo Local',
                    'must_change_password' => false,
                    'roles' => [
                        0 => 'Fornecedor',
                    ],
                ],
                6 => [
                    'name' => 'Comercial Expansao',
                    'email' => 'comercial.expansao@example.test',
                    'phone' => null,
                    'password' => 'password',
                    'is_active' => true,
                    'is_fornecedor' => false,
                    'is_lider_obra' => false,
                    'construtoras_id' => null,
                    'must_change_password' => false,
                    'roles' => [
                        0 => 'Comercial',
                    ],
                ],
                7 => [
                    'name' => 'PMO Expansao',
                    'email' => 'pmo.expansao@example.test',
                    'phone' => null,
                    'password' => 'password',
                    'is_active' => true,
                    'is_fornecedor' => false,
                    'is_lider_obra' => false,
                    'construtoras_id' => null,
                    'must_change_password' => false,
                    'roles' => [
                        0 => 'PMO',
                    ],
                ],
            ],
        ];
    }

    /**
     * @param  array<string, array{guard_name: string, permissions: list<string>}>  $roles
     */
    private function syncRolesAndPermissions(array $roles): void
    {
        foreach ($roles as $roleName => $roleData) {
            foreach ($roleData['permissions'] as $permissionName) {
                Permission::findOrCreate($permissionName, $roleData['guard_name']);
            }

            $role = Role::findOrCreate($roleName, $roleData['guard_name']);
            $role->syncPermissions($roleData['permissions']);
        }
    }

    /**
     * @param  list<array<string, mixed>>  $users
     */
    private function syncUsers(array $users): void
    {
        $defaultPasswordHash = Hash::make('password');

        foreach ($users as $userData) {
            $email = mb_strtolower((string) ($userData['email'] ?? ''));

            if ($email === '') {
                continue;
            }

            /** @var list<string> $roles */
            $roles = array_values(array_unique(array_filter(
                $userData['roles'] ?? [],
                static fn (mixed $role): bool => is_string($role) && $role !== '',
            )));

            DB::table('users')->updateOrInsert(
                ['email' => $email],
                [
                    'name' => (string) ($userData['name'] ?? $email),
                    'phone' => $this->nullableString($userData['phone'] ?? null),
                    'password' => $defaultPasswordHash,
                    'email_verified_at' => now(),
                    'is_active' => (bool) ($userData['is_active'] ?? true),
                    'is_fornecedor' => (bool) ($userData['is_fornecedor'] ?? false),
                    'is_lider_obra' => (bool) ($userData['is_lider_obra'] ?? false),
                    'construtoras_id' => $this->resolveConstrutoraId($userData),
                    'must_change_password' => (bool) ($userData['must_change_password'] ?? false),
                    'updated_at' => now(),
                    'created_at' => now(),
                ],
            );

            $user = User::query()->where('email', $email)->first();

            if ($user === null) {
                continue;
            }

            $user->syncRoles($roles);
        }
    }

    private function nullableString(mixed $value): ?string
    {
        if ($value === null) {
            return null;
        }

        $stringValue = trim((string) $value);

        return $stringValue === '' ? null : $stringValue;
    }

    private function nullableExistingForeignId(string $table, mixed $value): ?int
    {
        if ($value === null || $value === '') {
            return null;
        }

        $foreignId = (int) $value;

        if ($foreignId <= 0) {
            return null;
        }

        if (! DB::getSchemaBuilder()->hasTable($table)) {
            return null;
        }

        return DB::table($table)->where('id', $foreignId)->exists() ? $foreignId : null;
    }

    /**
     * @param  array<string, mixed>  $userData
     */
    private function resolveConstrutoraId(array $userData): ?int
    {
        $construtoraId = $this->nullableExistingForeignId('construtoras', $userData['construtoras_id'] ?? null);

        if ($construtoraId !== null) {
            return $construtoraId;
        }

        $construtoraNome = $this->nullableString($userData['construtora_nome'] ?? null);

        if ($construtoraNome === null || ! DB::getSchemaBuilder()->hasTable('construtoras')) {
            return null;
        }

        $resolvedId = DB::table('construtoras')
            ->whereRaw('LOWER(nome) = ?', [mb_strtolower($construtoraNome)])
            ->value('id');

        return $resolvedId ? (int) $resolvedId : null;
    }
}
